[platformio]
default_envs = fit_rig_esp32s3_10sps

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    bogde/HX711@^0.7.5
build_flags =
    -Wall
    -Wextra

[env:fit_rig_esp32s3_10sps]
build_flags =
    ${env.build_flags}
    -DX1_HX711_SPS=10

[env:fit_rig_esp32s3_80sps]
build_flags =
    ${env.build_flags}
    -DX1_HX711_SPS=80
